apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemodbapp
spec:
  ports:
  - port: 8090
  selector:
    app: kubernetesdemodbapp
  type: LoadBalancer
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kubernetesdemodbapp
spec:
  selector:
    matchLabels:
      app: kubernetesdemodbapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetesdemodbapp
    spec:
      containers:
      - image: lernen/kubernetesdemodbapp
        name: kubernetesdemodbapp
