apiVersion: v1
kind: Service
metadata:
  name: kubernetesDemoDbApp
spec:
  ports:
  - port: 8090
  selector:
    app: kubernetesDemoDbApp
  clusterIP: None
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kubernetesDemoDbApp
spec:
  selector:
    matchLabels:
      app: kubernetesDemoDbApp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetesDemoDbApp
    spec:
      containers:
      - image: lernen/kubernetesDemoDbApp
        name: kubernetesDemoDbApp
