apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-queue-listener
spec:
  ports:
  - port: 8080
  selector:
    app: kubernetes-demo-queue-listener
  type: ClusterIP
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kubernetes-demo-queue-listener
spec:
  selector:
    matchLabels:
      app: kubernetes-demo-queue-listener
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-demo-queue-listener
    spec:
      containers:
      - image: lernen/kubernetes-demo-queue-listener
        name: kubernetes-demo-queue-listener
