apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemoqueuesender
spec:
  ports:
  - port: 8080
  selector:
    app: kubernetesdemoqueuesender
  type: LoadBalancer
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kubernetesdemoqueuesender
spec:
  selector:
    matchLabels:
      app: kubernetesdemoqueuesender
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetesdemoqueuesender
    spec:
      containers:
      - image: lernen/kubernetesdemoqueuesender
        name: kubernetesdemoqueuesender
