apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-queue-sender
spec:
  ports:
  - port: 8080
  selector:
    app: kubernetes-demo-queue-sender
  type: ClusterIP
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kubernetes-demo-queue-sender
spec:
  selector:
    matchLabels:
      app: kubernetes-demo-queue-sender
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-demo-queue-sender
    spec:
      containers:
      - image: lernen/kubernetes-demo-queue-sender
        name: kubernetes-demo-queue-sender
