apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: lernen/demo_db
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        - name: MYSQL_DATABASE
          value: demo_db
        - name: MYSQL_USER
          value: sqluser
        - name: MYSQL_PASSWORD
          value: sqlpasswd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-ephemeral-storage
          mountPath: /var/lib/mysql
      volumes:
        # normally, one would use a persistent storage... this is a demo !
      - name: mysql-ephemeral-storage
        emptyDir: {}