apiVersion: v1
kind: Service
metadata:
  name: rabbit-container
spec:
  ports:
  - port: 5672
  selector:
    app: rabbit-container
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-managment
spec:
  ports:
  - port: 15672
  selector:
    app: rabbit-container
  type: LoadBalancer
---
#v1 for version >= 1.10
apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: rabbit-container
spec:
  selector:
    matchLabels:
      app: rabbit-container
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbit-container
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbit-container
